package com.j11a.dashboard.newsservice.model;

public enum Topic {
    NEWS, TECH, WORLD, FINANCE, POLITICS, BUSINESS, ECONOMICS, ENTERTAINMENT, BEAUTY, TRAVEL,
    MUSIC, FOOD, SCIENCE, GAMING, ENERGY, SPORT
}
